model:
  name: resnet18
  num_classes: 10

task:
  name: image_demo
  finished:
    max_steps: 100_000
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adamw

lr_scheduler:
  name: linear

trainer:
  name: sl
  batches_per_step: 4

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
