model:
  name: template

task:
  name: template
  finished:
    max_steps: 100_000
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adam
  lr: 3e-4

lr_scheduler:
  name: linear

trainer:
  name: vanilla_sl

logger:
  - name: stdout
  - name: tensorboard
